const mongoose=require('mongoose')
const formschema=new mongoose.Schema({
    email:{
        type:String,
        unique:true,
        required:true
    },
    name:{
        type:String,
        maxlength:50,
        minlength:5,
        required:true
    },
    currentContact:{
        type:Number,
        required:true
    },
    alternateContact:{
        type:Number,
        required:true
    },
    currentAddress:{
        type:String,
        minlength:10,
        required:true
    },
    permanentAddress:{
        type:String,
        minlength:10,
        required:true
    },
    Branch:{
        type:String,
        required:true
    },
    year:{
        type:Number,
        minlength:1,
        maxlength:1
    },
    bloodgroup:{
        type:String,
        required:true
    },
    belongToKIET:{
      type:String,
      minlength:5
    },
    knowAbout:{
        type:String,
        minlength:50,
        maxlength:250,
        required:true
    },
    heardAbout:{
        type:String,
        required:true
    },
    commitToWork:{
        type:String,
        required:true
    },
    otherSkill:{
        type:String,
        minlength:3,
        required:true
    },
    Suggestion:{
        type:String,
        minlength:10
    }
});
const Volunteer=mongoose.model('volunteer',formschema)
module.exports=Volunteer;